Repository thoth-station/sync-job, pull requests merged in 2020-07, with the labels that each got.

#4 Fix version identifier handling
  app.py
Labels: approved, size/XS

#6 Release of version 0.1.0
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS

#7 Make pre-commit happy
  OWNERS
  README.rst
Labels: approved, size/XS

#8 Automatic update of dependency thoth-storages from 0.24.2 to 0.24.3
  Pipfile.lock
Labels: approved, bot, size/M

#10 Add component name
  app.py
Labels: approved, size/XS

#11 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/S

#12 Sync solver first
  app.py
  openshift.yaml
Labels: approved, size/S

#14 Release of version 0.1.1
  CHANGELOG.md
  app.py
Labels: approved, bot

#15 Update of dependency thoth-storages from 0.24.3 to 0.24.4
  Pipfile.lock
Labels: size/S

#17 Release of version 0.1.2
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS

#20 Remove deadline for the job, it takes too much
  README.rst
  openshift.yaml
Labels: approved, size/S

#21 Automatic update of dependency thoth-storages from 0.24.4 to 0.24.5
  Pipfile.lock
Labels: approved, bot

#22 Automatic update of dependency thoth-common from 0.14.2 to 0.15.0
  Pipfile.lock
Labels: approved, bot, size/M
