Repository thoth-station/sync-job, pull requests merged in 2022-09, with the labels that each got.

#76 Remove pre-commit deps
  Pipfile
Labels: size/XS, lgtm

#78 :recycle: HouseKeeping: Updated pre-commit and OWNERS
  .pre-commit-config.yaml
  .prow.yaml
  .thoth.yaml
  OWNERS
Labels: size/S

#73 metrics
  Pipfile
  app.py
Labels: approved, size/M, lgtm

#79 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: approved, size/XS, ok-to-test
